# Generated by Django 5.1.1 on 2024-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='store_custo_last_na_5a62f0_idx'),
        ),
    ]
